ALTER ROLE miioofd WITH SUPERUSER CREATEROLE CREATEDB LOGIN;
GRANT ALL ON SCHEMA public TO miioofd;
GRANT ALL ON ALL TABLES IN SCHEMA public TO miioofd;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO miioofd;
ALTER ROLE miioofd WITH BYPASSRLS;
